version: '3'
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1452
services:
  gradle_build:
    image: gradle:7.5.1-jdk17
    container_name: gradle_build
    environment:
      - SERVICE_ENDPOINT=${SERVICE_ENDPOINT}
    volumes:
      - .:/opt/app
    working_dir: /opt/app

  service:
    container_name: service
    hostname: service
    environment:
      - DOWNSTREAM_HOST=podinfo
      - POSTGRES_HOST=database
    build:
      dockerfile: ./Dockerfile.service
      context: .
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/hello"]
      interval: 5s
      retries: 5
      start_period: 20s
      timeout: 10s
    depends_on:
      database:
        condition: service_healthy
  k6:
    image: grafana/k6
    volumes:
      - .:/opt/app
    working_dir: /opt/app

  downstream:
    container_name: podinfo
    hostname: podinfo
    image: stefanprodan/podinfo:6.2.2
    ports:
      - "9898:9898"

  database:
    container_name: database
    hostname: database
    image: 'postgres:15.0-bullseye'
    ports:
      - 5432:5432
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=password

  waitForHealthyPods:
    image: alpine:latest
    depends_on:
      service:
        condition: service_healthy