baseURL = 'your-base-url'
languageCode = 'en-us'
# Title of your site
title = 'My Bootcamp'
# The theme. This needs to stay as it is.
theme = 'hugo-theme-learn'
enableEmoji = true
# Title separator -- defaults to ::
titleSeparator = "-"
[params]
# Theme variant, green, red and blue are available out of the box.
# You can also use a custom theme, as per the name you've given your theme.css file. E.g, theme-cecg.css
  themeVariant = "cecg"
# Enable search
[outputs]
  home = [ "HTML", "RSS", "JSON"]